// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDubvtzLVNu3-DzG7jvQNKVXhSwKycpWZU',
    appId: '1:385546667072:web:8a5cde040044c79b354ba5',
    messagingSenderId: '385546667072',
    projectId: 'yemae-app',
    authDomain: 'yemae-app.firebaseapp.com',
    storageBucket: 'yemae-app.firebasestorage.app',
    measurementId: 'G-3V5VSXFK71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC514mtofulh0-RvSnLVJaNTu3LpM0WMrw',
    appId: '1:385546667072:android:af27f16557c331b9354ba5',
    messagingSenderId: '385546667072',
    projectId: 'yemae-app',
    storageBucket: 'yemae-app.firebasestorage.app',
  );
}
